# Generated by Django 5.2.1 on 2025-11-15 10:06

import datetime
import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "year",
                    models.IntegerField(
                        default=2025,
                        help_text="比赛举办年份",
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2200),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("logo", models.TextField(blank=True, null=True)),
                ("place", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("local", "local"),
                            ("regional", "regional"),
                            ("national", "national"),
                            ("international", "international"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("top", "top"),
                            ("A_level", "A_level"),
                            ("B_level", "B_level"),
                            ("C_level", "C_level"),
                            ("D_level", "D_level"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "months",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(12),
                            ]
                        ),
                        default=list,
                        size=12,
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("AI", "AI"),
                                ("CS", "CS"),
                                ("IS", "IS"),
                                ("EE", "EE"),
                                ("math", "math"),
                                ("innovation", "innovation"),
                                ("others", "others"),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "materials",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="学习资料列表，格式：[{'name': '资料名称', 'url': '链接'}]",
                    ),
                ),
                (
                    "registration_start",
                    models.DateTimeField(
                        default=datetime.datetime(1234, 5, 6, 7, 8, 9)
                    ),
                ),
                (
                    "registration_end",
                    models.DateTimeField(
                        default=datetime.datetime(1234, 5, 6, 7, 8, 9)
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contest",
                "verbose_name_plural": "Contests",
            },
        ),
    ]
