# Generated by Django 5.2.1 on 2025-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="level",
            field=models.CharField(
                choices=[
                    ("local", "local"),
                    ("regional", "regional"),
                    ("national", "national"),
                    ("international", "international"),
                    ("others", "others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="quality",
            field=models.CharField(
                choices=[
                    ("top", "top"),
                    ("A_level", "A_level"),
                    ("B_level", "B_level"),
                    ("C_level", "C_level"),
                    ("D_level", "D_level"),
                    ("others", "others"),
                ],
                max_length=50,
            ),
        ),
    ]
