# Generated by Django 5.2.1 on 2025-11-15 10:07

import SJTUcontest.utils
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="队伍名称", max_length=50)),
                (
                    "introduction",
                    models.CharField(
                        blank=True, help_text="队伍简介", max_length=500, null=True
                    ),
                ),
                (
                    "existing_members",
                    models.PositiveIntegerField(default=1, help_text="队伍已有人数"),
                ),
                (
                    "expected_members",
                    models.PositiveIntegerField(help_text="队伍期望人数"),
                ),
                (
                    "recruitment_deadline",
                    models.DateTimeField(help_text="招募截止日期"),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        default=SJTUcontest.utils.generate_random_string,
                        help_text="队伍邀请码",
                        max_length=40,
                    ),
                ),
                (
                    "invitation_code_created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="邀请码创建时间"
                    ),
                ),
                (
                    "is_invitation_code_valid",
                    models.BooleanField(default=True, help_text="邀请码是否有效"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contest",
                    models.ForeignKey(
                        help_text="队伍要参加的比赛",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="contests.contest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="UserTeam",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "is_leader",
                    models.BooleanField(default=False, help_text="是否为队长"),
                ),
                (
                    "join_date",
                    models.DateTimeField(auto_now_add=True, help_text="加入队伍的日期"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_users",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserTeam",
                "verbose_name_plural": "UserTeams",
            },
        ),
    ]
